// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5jXLO2YyVTt6ihn4hmpT0WKViv_vD8mk',
    appId: '1:138549974499:web:416bb90ed104e242bcfcd6',
    messagingSenderId: '138549974499',
    projectId: 'x-ray-2c7c1',
    authDomain: 'x-ray-2c7c1.firebaseapp.com',
    storageBucket: 'x-ray-2c7c1.appspot.com',
    measurementId: 'G-8LPVZXSBPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6zhP_3NDZpHNyv495K47jwoVpLeoJmJk',
    appId: '1:138549974499:android:3b5fb75a481583b3bcfcd6',
    messagingSenderId: '138549974499',
    projectId: 'x-ray-2c7c1',
    storageBucket: 'x-ray-2c7c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUjXg6H6tVyYkmc_wR4yzPvjQ038e4oOQ',
    appId: '1:138549974499:ios:300fda7ce6d2129ebcfcd6',
    messagingSenderId: '138549974499',
    projectId: 'x-ray-2c7c1',
    storageBucket: 'x-ray-2c7c1.appspot.com',
    iosBundleId: 'com.example.xRay2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUjXg6H6tVyYkmc_wR4yzPvjQ038e4oOQ',
    appId: '1:138549974499:ios:300fda7ce6d2129ebcfcd6',
    messagingSenderId: '138549974499',
    projectId: 'x-ray-2c7c1',
    storageBucket: 'x-ray-2c7c1.appspot.com',
    iosBundleId: 'com.example.xRay2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5jXLO2YyVTt6ihn4hmpT0WKViv_vD8mk',
    appId: '1:138549974499:web:aa149390044c741dbcfcd6',
    messagingSenderId: '138549974499',
    projectId: 'x-ray-2c7c1',
    authDomain: 'x-ray-2c7c1.firebaseapp.com',
    storageBucket: 'x-ray-2c7c1.appspot.com',
    measurementId: 'G-ZSTRF0F4Z0',
  );

}