// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7oYeuViyBoktW7URP_bME1JSFjN9gUNg',
    appId: '1:813412901326:web:493ce95c316bf24d058b9f',
    messagingSenderId: '813412901326',
    projectId: 'x-ray-123',
    authDomain: 'x-ray-123.firebaseapp.com',
    storageBucket: 'x-ray-123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpnQm1HGAPcM96f-cY5LGitlc2M51pF4Q',
    appId: '1:813412901326:android:4eff15391006efe0058b9f',
    messagingSenderId: '813412901326',
    projectId: 'x-ray-123',
    storageBucket: 'x-ray-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzOxQKjQ8teJAGmq3wx3ledqg_nsi4hqk',
    appId: '1:813412901326:ios:7e7507b73d5fcbfa058b9f',
    messagingSenderId: '813412901326',
    projectId: 'x-ray-123',
    storageBucket: 'x-ray-123.appspot.com',
    androidClientId: '813412901326-p9gpkhb6lbmg2l7la2pcjiej2944hrin.apps.googleusercontent.com',
    iosClientId: '813412901326-ss33icqflgv7q9pnot0fsm1mnl3bduuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.xRay2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzOxQKjQ8teJAGmq3wx3ledqg_nsi4hqk',
    appId: '1:813412901326:ios:7e7507b73d5fcbfa058b9f',
    messagingSenderId: '813412901326',
    projectId: 'x-ray-123',
    storageBucket: 'x-ray-123.appspot.com',
    androidClientId: '813412901326-p9gpkhb6lbmg2l7la2pcjiej2944hrin.apps.googleusercontent.com',
    iosClientId: '813412901326-ss33icqflgv7q9pnot0fsm1mnl3bduuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.xRay2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7oYeuViyBoktW7URP_bME1JSFjN9gUNg',
    appId: '1:813412901326:web:3f7dac5d2384c3ff058b9f',
    messagingSenderId: '813412901326',
    projectId: 'x-ray-123',
    authDomain: 'x-ray-123.firebaseapp.com',
    storageBucket: 'x-ray-123.appspot.com',
  );

}